name: CI
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'assets/**'
      - 'generators/**'
      - 'build.ts'

jobs:
  get-subdomain:
    runs-on: ubuntu-20.04
    outputs:
      SUBDOMAIN: ${{ steps.extract-branch.outputs.SUBDOMAIN }}
    steps:
      - name: Extract Branch Name
        id: extract-branch
        run: |
          echo SUBDOMAIN=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | perl -pe 's/[^a-zA-Z0-9]+/-/g and s/-+$//g' | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
  deploy-property:
    needs:
      - get-subdomain
    uses: ./.github/workflows/akamai_deploy_property.yml
    with:
      subdomain: ${{ needs.get-subdomain.outputs.SUBDOMAIN }}
