name: CI
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract Branch Name
        id: extract-branch
        run: |
          echo BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT
      - name: Echo Branch Name
        run: |
          echo  ${{steps.extract-branch.outputs.BRANCH_NAME}}
