name: CI
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract Branch Name
        id: extract-branch
        run: |
          echo BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT
      - name: Create Cloudflare DNS Record
        run: |
          curl --location --request POST 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/dns_records' \
          --header 'Content-Type: application/json' \
          --header 'X-Auth-Email: ${{ secrets.CF_AUTH_EMAIL }}' \
          --header 'Authorization: Bearer ${{ secrets.CF_AUTH_TOKEN }}' \
          --data-raw '{
            "content": "${{steps.extract-branch.outputs.BRANCH_NAME}}.cfi-fingerprint.com.edgesuite.net",
            "name": "${{steps.extract-branch.outputs.BRANCH_NAME}}.cfi-fingerprint.com",
            "proxied": false,
            "type": "CNAME",
            "comment": "Akamai CI run for ${{steps.extract-branch.outputs.BRANCH_NAME}}",
            "tags": [
              "owner:akamai"
            ],
            "ttl": 3600
          }'