name: Test e2e

on:
  pull_request_target:
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:


jobs:
  build-and-deploy-and-test-e2e:
    runs-on: ubuntu-20.04
    name: Build & Deploy & Test e2e
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: npx playwright install
      - name: Run test
        run:  yarn test:e2e
        env:
          TEST_DOMAIN: ${{secrets.TEST_DOMAIN}}
          TEST_RESULT_DOMAIN: ${{secrets.TEST_RESULT_DOMAIN}}
          TEST_RESULT_PATH: ${{secrets.TEST_RESULT_PATH}}
          INTEGRATION_PATH: ${{secrets.INTEGRATION_PATH}}
          RESULT_PATH: ${{secrets.RESULT_PATH}}
          AGENT_PATH: ${{secrets.AGENT_PATH}}
          FPJS_API_KEY: ${{secrets.FPJS_API_KEY}}
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@0d9c6ff1de9903da88d24c0564f6e83cb28faca9
        with:
          status: ${{ job.status }}
          notification_title: "Akamai E2E Test has {status_message}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}