name: Test e2e

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:


jobs:
  build-and-test-e2e:
    runs-on: ubuntu-20.04
    name: Build & Deploy & Test e2e
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: npx playwright install
      - name: Run test
        run:  yarn test:e2e
        env:
          TEST_DOMAIN: ${{secrets.TEST_DOMAIN}}
          TEST_RESULT_DOMAIN: ${{secrets.TEST_RESULT_DOMAIN}}
          TEST_RESULT_PATH: ${{secrets.TEST_RESULT_PATH}}
          INTEGRATION_PATH: ${{secrets.INTEGRATION_PATH}}
          RESULT_PATH: ${{secrets.RESULT_PATH}}
          AGENT_PATH: ${{secrets.AGENT_PATH}}
          FPJS_API_KEY: ${{secrets.FPJS_API_KEY}}
  report-status:
    needs: build-and-test-e2e
    if: always()
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
    with:
      notification_title: 'Akamai E2E Test: {status_message}'
      job_status: ${{ needs.build-and-test-e2e.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}