name: Test e2e for PR

on:
  pull_request:

jobs:
  build-and-test-e2e:
    runs-on: ubuntu-20.04
    name: Build & Deploy & Test e2e
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: npx playwright install
      - name: Extract Branch Name
        id: extract-branch
        run: |
          echo SUBDOMAIN=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | perl -pe 's/[^a-zA-Z0-9]+/-/g and s/-+$//g' | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
      - name: Run test
        run:  yarn test:e2e
        env:
          TEST_DOMAIN: 'https://${{steps.extract-branch.outputs.SUBDOMAIN}}.${{secrets.FPJS_CI_DOMAIN}}'
          TEST_RESULT_DOMAIN: ${{secrets.TEST_RESULT_DOMAIN}}
          TEST_RESULT_PATH: ${{secrets.TEST_RESULT_PATH}}
          INTEGRATION_PATH: ${{secrets.INTEGRATION_PATH}}
          RESULT_PATH: ${{secrets.RESULT_PATH}}
          AGENT_PATH: ${{secrets.AGENT_PATH}}
          FPJS_API_KEY: ${{secrets.FPJS_API_KEY}}
