name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Build project, run CI checks and publish new release'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      runnerAppId: ${{ vars.RUNNER_APP_ID }}
      version-command: pnpm exec changeset version
      publish-command: pnpm exec changeset publish
      language: node
      language-version: 24
      prepare-command: pnpm build
      github-release-files: "dist/terraform/terraform-*.json"
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      RUNNER_APP_PRIVATE_KEY: ${{ secrets.RUNNER_APP_PRIVATE_KEY }}
